pipeline-notebooks/pipeline-general.ipynb, prepline_general/api/general.py
Closes #41 and writes the `SpooledTemporaryFile` file-like object to a temporary file so that we can process `.pptx` and `.docx` files. This is an issue with the `SpooledTemporaryFile` wrapper itself. Per [this post](https://stackoverflow.com/questions/47160211/why-doesnt-tempfile-spooledtemporaryfile-implement-readable-writable-seekable), it does not have a `seekable` attribute, which is required to read the file in `python-docx` and `python-pptx`.
Note, this is a bit of a hacky fix and long term it would be better to:
- Fix this in `unstructured-api-tools`
- Limit the temp file behavior to `.pptx` and `.docx`, since it's an unnecessary read/write otherwise.
Run `make run-web-app` and then do the following `curl` commands. You should see JSON output, where previously these calls produced …
=> fix: write to temp files to support .pptx and .docx

CHANGELOG.md, Makefile, README.md, exploration-notebooks/exploration-email.ipynb, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, requirements/base.in, requirements/base.txt, requirements/test.txt, scripts/smoketest.py, test_general/api/test_app.py
Follow up now that https://github.com/Unstructured-IO/unstructured-api-tools/pull/141 is merged.
This is a big diff, but for the record this is just:
* Bump unstructured-api-tools (and unstructured) in base.in
* Run `make pip-compile` to regen requirements files and `make install`
* Run `make generate-api`
* Remove the time.sleep lines from the tests
=> chore: bump core dependencies and remove old rate limiting

Dockerfile
Sometimes a log message appears about /usr/local/bin/pip even though it is not the root cause of a python error.
This commit is to address that distraction (hopefully).
=> chore: pip workaround

CHANGELOG.md, README.md, pipeline-notebooks/pipeline-general.ipynb, prepline_general/api/general.py, scripts/smoketest.py, test_general/api/test_app.py
* adds an `m_strategy` parameter with a string default of [“fast”] to `pipeline_api`
* adds a smoke test that tests the timing of a PDF with both strategies and verifies `fast` is _much_ faster than `hi_res`
* adds a unit test that validates a 400 error for any other value for `strategy`
* adds README mention of this functionality
I ran the new smoke test on both the local mac and a remote dev instance. Both were clear the 4x threshold that we're testing against.
- Run the app (`make run-web-app` or preferred method that runs on localhost)
- Run the smoke test: `PYTHONPATH=. pytest scripts/smoketest.py::test_strategy_performance`
You can test any request with:
```
curl -X 'POST' \
'http://localhost:8000/general/v0/general' \
-H 'accept: application/json' \
-H 'Content-Type: …
```
=> feat: add an m_strategy parameter to pipeline_api

CHANGELOG.md, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, requirements/base.txt, requirements/test.txt, test_general/api/test_app.py
Bump unstructured-api-tools which has more a descriptive message in HTTP 400 responses
for unsupported file types.
=> build(deps): bump unstructured-api-tools

README.md
Clean up some of the curl examples.
I think the readme on the whole can flow a bit better, but the priority right now is to document how to hit the hosted api.
=> Add hosted API callout to the README

CHANGELOG.md, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, requirements/base.txt, requirements/test.txt, scripts/smoketest.py
When requests doesn't specify a content type, the server recieves None, which should be handled like octet-stream. We can verify that by removing the content type arg from the smoke test. All filetypes come back with a 400 error until we introduce the fix.
=> chore: bump api-tools version to get content_type fix

prepline_general/api/app.py, requirements/base.txt, requirements/test.txt
This is to grab the change from https://github.com/Unstructured-IO/unstructured-api-tools/pull/164 and ensure we serve the api spec at /general/openapi.json.
=> Update api-tools version and fix openapi_url

CHANGELOG.md, Dockerfile, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, requirements/base.in, requirements/base.txt, requirements/test.txt
Currently building the Docker image from am M1 Mac results in an error when attempting to install detectron. It will error with:  `ModuleNotFoundError: No module named 'torch'`. Torch is in fact installed. It appears the issue is actually resolved by installing Tensorboard. This adds a step to install tensorboard just before installing detectron.
* update image build steps so that detectron2 will install when built from Mac M1
* update image build steps to upgrade to openssl 1.1.1 which is needed for urllib3
* bonus: bump unstructured for fixes for SpooledTemporaryFile support
* prior to these changes, run `make docker-build`.
* validate that this error with ` ModuleNotFoundError: No module named 'torch`
* pull in these changes and run `make docker-build` again
* this time it should …
=> fix: image build from m1 

Dockerfile, pipeline-notebooks/pipeline-general.ipynb, prepline_general/api/general.py
Since we now push docx and pptx files into BytesIO in unstructured we no longer need to write them to a temporary file in the pipeline.
Also we no longer need to attempt to downgrade urllib since we have openssl 1.1.1 install in the image build. Removes downgrade step.
* Undo special handling of docx and pptx getting written to temp file
* bonus: Undo revertting to urllib<2
=> chore: remove docx and pptx writing to file

CHANGELOG.md, logger_config.yaml, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml
Config for `unstructured.trace` logger since it is added in the `unstructured` repo. The NLP `DEBUG` level log from `unstructured` logger is moved to `unstructured.trace` logger of `DETAIL` level.
* Install latest version of `unstructured` in your env with `install-project-local`
* Set logger level for `unstructured` logger to `DEBUG`
* Run  `make run-web-app` and make an API call
The log output will only contain `INFO` level logs. i.e,
```
2023-05-10 13:16:42,130 uvicorn.error INFO Application startup complete.
2023-05-10 13:16:46,388 127.0.0.1:62057 POST /general/v0/general HTTP/1.1 - 200 OK
```
To see the NLP `DEBUG` log, set logger level for `unstructured.trace` logger to `DEBUG` and run the test again. The log output should look like:
```
2023-05-10 13:19:13,751 unstructured.trace …
```
=> Chore: Add config for unstructured.trace logger

CHANGELOG.md, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, requirements/base.txt, requirements/test.txt
Bumping the version and running `make generate-api` to add CORS support to the API if `ALLOWED_ORIGINS` is set. https://github.com/Unstructured-IO/unstructured-api-tools/pull/172
=> chore: bumping api version

Dockerfile
This should speed up the builds a lot by using a docker image that has all the required system libraries and packages compiled/installed.
You can find the Dockerfile for the base image at https://github.com/Unstructured-IO/base-images or pull them from quay at quay.io/unstructured-io/base-images:centos7.9
The base image has been built for both linux/arm64 and linux/amd64 using docker buildx
=> chore: CORE-863 Build image from base image

CHANGELOG.md, Dockerfile, README.md, prepline_general/api/general.py, preprocessing-pipeline-family.yaml
The images pushed to quay.io will now have python 3.8.17 rather than python 3.8.15.
=> chore: bump python to 3.8.17

CHANGELOG.md, pipeline-notebooks/pipeline-general.ipynb, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, requirements/base.in, requirements/base.txt, requirements/test.txt
From warning:
```
../../.pyenv/versions/unstructured-api/lib/python3.8/site-packages/PyPDF2/_init _.py: 21
/Users/yumingl/.pyenv/versions/unstructured-api/lib/python3.8/site-packages/PyPDF2/ ease move to the pypdf library instead.
warnings.warn
_init_.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
```
no warning from `make test`
=> Chore: deprecate pypdf2 and move it to pypdf

scripts/docker-build.sh, scripts/docker-smoke-test.sh, scripts/shellcheck.sh, scripts/version-sync.sh
Update all bash scripts with #!/bin/bash to use /usr/bin/env bash.
=> chore: update all bash scripts to use shebang: /usr/bin/env bash

.github/workflows/docker-publish.yml
Fixes issue where arm64 docker builds were failing and preventing images from being published.
The latest main commit plus this branch (1st commit) has already been published in CI here: 
https://github.com/Unstructured-IO/unstructured-api/actions/runs/5428856738/jobs/9873551850
=> build(image): docker build tweak for arm64

.github/workflows/docker-publish.yml
This isn't necessarily a fix for the missing .venv, but this will remove an extra 2GB cache called ci-venv--{commit} and reuse ci-venv-general-{commit}.
Also, don't delete the $AGENT_TOOLSDIRECTORY dir. Testing shows this is `/opt/hostedtoolcache`. No immediate connection to the cache action, which seems to use `/home/runner/work/_temp`, but I did manage to get past the bad interpreter error by keeping this dir.
=> fix: share the cache from the CI workflow

CHANGELOG.md, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, scripts/docker-smoke-test.sh
Don't complain when stopping a container that doesn't exist.
=> chore: Remove a misleading error in docker smoketest

CHANGELOG.md, pipeline-notebooks/pipeline-general.ipynb, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, test_general/api/test_app.py
This was a subtle bug that came out in the retry logic. When we get a 500 during the requests.post, we'll try again. However, the pdf was stored in a BytesIO, which had already been read the first time we sent it. The next request sends an empty file, which results in a 400 response masking the original error.
Steps to verify:
* First, checkout `main`
* Start up the api in parallel mode
```
export UNSTRUCTURED_PARALLEL_MODE_ENABLED=true
export UNSTRUCTURED_PARALLEL_MODE_URL=http://localhost:8000/general/v0/general
make run-web-app
```
* Insert a 500 error into `prepline_general/api/general.py:partition_pdf_splits()`
```
if len(pdf_pages) <= pages_per_pdf:
raise HTTPException(status_code=500)  # Throw an error here
return partition(
file=file, file_filename=file_filename, …
```
=> fix: fix "not a valid pdf error" in parallel mode

CHANGELOG.md, pipeline-notebooks/pipeline-general.ipynb, prepline_general/api/general.py
To verify, you need to run parallel mode and send a pdf file with the correct mimetype but a wrong file extension.
On main, start the server in parallel mode and confirm the bug happens:
```
export UNSTRUCTURED_PARALLEL_MODE_ENABLED=true
export UNSTRUCTURED_PARALLEL_MODE_URL=http://localhost:8000/general/v0/general
make run-web-app
```
In a python shell:
```
import requests
with open("sample-docs/layout-parser-paper.pdf", "rb") as f:
res = requests.post("http://localhost:8000/general/v0/general",
files={"files": ("foo.txt", f, "application/pdf")})
print(res.text)
```
Then try again on this branch.
Also, removed logging of the request object, which just displays an object reference next to the params.
=> fix: fix occasional UnboundLocalError

.github/dependabot.yml, .github/workflows/bump_libraries.yaml, CHANGELOG.md, scripts/version-increment.sh
- Set dependabot to run daily and only pick up unstructured changes
- Add `version-increment.sh` to add a line to the changelog and cut a release
- Add a new action, triggered off dependabot prs, to run version-increment on pr branch
I may have the syntax a bit off, so we'll see what happens when dependabot runs next.
=> enhancement(deps): cut a release when unstructured libs are bumped

.github/workflows/bump_libraries.yaml
The default env will produce a different set of packages when the gh action does `make pip-compile`.
=> chore: use correct python version when running pip-compile in workflow

CHANGELOG.md, prepline_general/api/app.py
This improves on https://github.com/Unstructured-IO/unstructured-api/pull/224. My first attempt dumps the stack for any HttpException, which means any explicit 400, etc, that we raise. What we really want is the stack trace for unexpected errors, that is, anything that isn't HttpException.
* Move the stack dump to the base Exception handler
* Log `e.detail` in the HttpException handler. This is also important - we want to see what the user ran into.
* Disable the `uvicorn.error` logger, which also dumps stack on any exception. We want that to go through our handler.
To test, use the curl commands from the last pr.
The HttpException (filetype not supported error) should cleanly show as a one liner:
```
2023-09-15 12:06:13,570 unstructured_api ERROR Unable to process logger_config.yaml: …
```
=> chore: do not log stack traces for HttpException

CHANGELOG.md, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, test_general/api/test_app.py
This field was added to the metadata in `unstructured==0.10.13`, and it was deployed to the hosted api [last week](https://github.com/Unstructured-IO/unstructured-api/releases/tag/0.0.43). When users called `partition_via_api` with older versions of the library, they saw an error related to parsing the new schema. We should fix backwards compatibility in the library, but in the meantime let's drop the new field; it's not super relevant to the end user.
Closes #237
=> fix: drop detection_class_prob from element metadata

CHANGELOG.md, README.md, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, test_general/api/test_app.py
Add `chunking_strategy` as a kwarg for parsing and associated test.
```
curl -X 'POST' 'http://127.0.0.1:8000/general/v0/general' \
-H 'accept: application/json'  \
-H 'Content-Type: multipart/form-data' \
-F 'files=@sample-docs/layout-parser-paper-fast.pdf' \
-F 'chunking_strategy=by_title' \
| jq -C . | less -R
```
=> feat: add chunking_strategy kwarg

CHANGELOG.md, prepline_general/api/general.py
Original issue: https://github.com/Unstructured-IO/unstructured-api/issues/237
Core library fix: https://github.com/Unstructured-IO/unstructured/pull/1526
Anyone who calls `partition_via_api` will hit this bug until they upgrade `unstructured`, which includes any Langchain users of `UnstructuredAPIFileLoader`. The immediate fix is to remove `parent_id` from the hosted api. Next, we can ensure that [langchain users](https://github.com/langchain-ai/langchain/pull/11025) are up to date. Finally, the core library fix above will address any new fields going forward. It will be safe to readd the `parent_id` once users are generally on `unstructured>=0.10.15`.
=> fix: remove `parent_id` until backwards compat bug is addressed

CHANGELOG.md, prepline_general/api/general.py, test_general/api/test_app.py
Fixes #236 
The `pdf.is_encrypted` check is true for files with edit protections, so we were returning 400 "This file is encrypted" for files that were perfectly readable. To verify, run this branch with `make run-web-app` and submit the pdf in the linked issue.
Other changes:
* Remove filename from some error messages. This can get way too verbose.
=> fix: Do not return 400 error for encrypted but readable pdfs

Makefile, prepline_general/api/app.py, prepline_general/api/general.py
These were excluded from linting when they were autogenerated. We need to tidy these files, otherwise we'll get blocked by our internal deploy pipeline.
Note that this should replace the current 0.0.47 candidate.
=> chore: run make tidy on api files

CHANGELOG.md, Makefile, prepline_general/api/app.py, prepline_general/api/general.py
* Set the current version in the FastAPI constructor and use `app.version` elsewhere
* Update version-sync commands accordingly
* Do not dump stack traces for unhandled errors
* Add a startup log, other startup is silent without `uvicorn.error`
=> chore: start using the FastAPI version and other cleanup

Dockerfile
New base image includes security fixes.  This is an ongoing process to remediate security issues as they are identified.
=> Bump Dockerfile to use latest base image

.github/dependabot.yml, .github/workflows/bump_libraries.yaml
Given this fix: https://github.com/Unstructured-IO/unstructured/pull/1474
We should get the correct inference whenever unstructured is bumped. We can't take these out of order. Also tweak the gh action to remove `[local-inference]` when `bumping unstructured` message is added.
=> chore: don't let dependabot pull unstructured-inference

CHANGELOG.md, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, test_general/api/test_app.py
In many cases these are tempfiles and just create additional noise.
=> Remove filenames from BadZipFile error message

CHANGELOG.md, prepline_general/api/general.py
We've seen this error in the hosted api:
```
UnboundLocalError: local variable 'elements' referenced before assignment
File "prepline_general/api/general.py", line 649, in response_generator
response = pipeline_api(
File "prepline_general/api/general.py", line 464, in pipeline_api
for i, element in enumerate(elements):
```
The if block in the check for `zipfile.BadZipFile` allows us to fall through without assigning `elements`. Instead, we should raise a 400 error when we catch this exception.
=> fix: fix local variable 'elements' referenced before assignment

Dockerfile
The ssh keyscan and authorized_hosts file is no longer needed as private repos are not being cloned.  Removing this reduces false positives from scanners.
=> remove keyscan and ssh files as they are no longer needed.

CHANGELOG.md, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml
This was removed in #252 to address a backwards compat bug in Langchain. The bug was fixed in unstructured 0.10.15 and this is now the min version in Langchain.
=> chore: reintroduce parent_id metadata field

CHANGELOG.md, Makefile, prepline_general/api/general.py, scripts/app-start.sh, test_general/api/test_app.py
Chipper V2 is very memory hungry. While we work to optimize this, we need to restrict the server to one call at a time. While the model is in use, we'll return a 503 "Please try again". Our hosted API should scale up to meet demand, so the next call should route to an available server.
This includes a refactor to how partition_kwargs are passed to either parallel mode, local partition, or local partition with the new Chipper protection.
To verify, try calling Chipper twice:
```
curl -X POST 'http://localhost:8000/general/v0/general' --form files="@$file" --form strategy=hi_res --form hi_res_model_name=chipper &
curl -X POST 'http://localhost:8000/general/v0/general' --form files="@$file" --form strategy=hi_res --form hi_res_model_name=chipper
```
The second call will get a 503 response. …
=> feat: Only allow one Chipper call at a time

CHANGELOG.md, prepline_general/api/general.py
We want this to alias to the current model. Also, wrap the error that comes from chipperv1 becoming a private model.
To verify:
* Run the server
```
make run-web-app
```
* A call to chipperv1 should give a useful error:
```
curl -X POST 'http://localhost:8000/general/v0/general' --form files="@$file" --form strategy=hi_res --form hi_res_model_name=chipperv1
{"detail":"The Chipper model is not available for download. It can be accessed via the official hosted API."}
```
* Change the model name to `chipper`. You should see `chipperv2` in the log message containing partition input data
=> chore: remap `chipper` to use `chipperv2`

Makefile
This variable isn't relevant when developing with the public image.
=> chore: Remove huggingface token passthrough in makefile

prepline_general/api/general.py, test_general/api/test_app.py
Closes #314
We don't support any fallback for fast strategy on images anymore, and unst will raise [value error](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/strategies.py#L22) if partition uses fast strategy for image files. This catches the error and raises a 400 HTTPException.
Also, this refactors `pipeline_api` to extract out some validation of arguments.
=> catch 500 error for fast strategy

prepline_general/api/general.py, test_general/api/test_app.py
Closes #323 
Certain OSErrors come back with an errno in the first arg. We were searching for a substring in here, so we just need to skip the check if e.args[0] is not a string.
The new test case verifies this by raising an error with a errno.
=> fix: handle argument of type 'int' is not iterable

prepline_general/api/general.py
Clarify what's causing the error for the user. To test, set the free minimum really high and check that the log message shows.
```
export UNSTRUCTURED_MEMORY_FREE_MINIMUM_MB=16000
make run-web-app
file=sample-docs/layout-parser-paper.pdf
curl -X POST 'http://localhost:8000/general/v0/general' --form files="@$file"
```
=> chore: add a log message when returning 503 due to low memory

CHANGELOG.md, README.md, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, test_general/api/test_app.py
This PR gives people the ability to use the API key header to validate requests when self-hosting Unstructured. If the optional environment variable of  `UNSTRUCTURED_API_KEY` does not match the request header of `unstructured-api-key`, then we fail with a `401` response instead of fulfilling the request.
This will allow people to self-host unstructured with confidence that only internal applications that have access to the shared key can use the service.
Closes https://github.com/Unstructured-IO/unstructured-api/issues/321
=> feat: add support for API key validation for self-hosted

prepline_general/api/general.py, test_general/api/test_app.py
Closes #326. Differentiate unprocessable entity errors from incorrect parameters, etc.
=> feat: return 422 errors for unprocessable files

CHANGELOG.md, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, test_general/api/test_app.py
Closes #330 
Raises 400 error if hi_res_model_name is an unknown model.
=> Handle unknown hi_res_model_name

CHANGELOG.md, requirements/base.txt, requirements/test.txt
This will close #333 which has been fixed in the library.
=> chore(deps): bump unstructured

prepline_general/api/general.py, test_general/api/test_app.py
Add a new route handler for handling GET requests for the /general/v0/general. This handler will return the error message that informs user that GET request is not permitted.
=> Klaijan/add error detail on GET request

Dockerfile
The fix for openssl has been reverted: https://github.com/Unstructured-IO/base-images/pull/13
Need to confirm that this digest is still valid. If the docker test fails in this branch, we'll need to wait until the new image has been built. Edit: yeah, I've written over the existing base-image which may break self hosted users who are building from source with an older dockerfile. Will update the digest once the new image is out.
=> chore: revert base image change

openapi.json
The clients are doing exponential backoff for up to an hour which is way too long. To verify, we'll need to wait for the client repos to get regenerated.
=> Set Speakeasy max retry time to 5 minutes

CHANGELOG.md, prepline_general/api/app.py, prepline_general/api/general.py, preprocessing-pipeline-family.yaml, pyproject.toml, test_general/api/test_app.py
This is the minimal fix for the `combine_text_under_n_chars` arg-name typo bug described in #337.
Chunking parameters were added to the API about 4 months ago in this commit: https://github.com/Unstructured-IO/unstructured-api/commit/49fe71026e026530276bbb72f6a9df46feb6d1c2
At that time, the identifier `combine_under_n_chars` was used instead of `combine_text_under_n_chars` (as that parameter appears in `chunk_by_title()`). As a result, any value supplied for this argument via the REST API is ignored and defaults to 500. The `combine_under_n_chars` parameter name  appears in the API documentation and elsewhere (README.md etc.) and differs from the parameter name documented for `chunk_by_title()`.
A fuller remedy will be to add a separate `combine_text_under_n_chars` parameter to the API …
=> fix(chunking): minimal fix for combine arg typo

prepline_general/api/general.py
Added `include_in_schema=False` in corresponding handlers
Resolves #347
=> feat: hide GET helper handlers in swagger/schema

prepline_general/api/general.py
Related to https://github.com/Unstructured-IO/unstructured/pull/2446 . Adds YAML to the list of default MIME types. Had originally through to dynamically build the list from the MIME types in `unstructured`, but there are some MIME types (like `audio/wav` that are currently support for filetype detection but not `partition`. Probably want to be deliberate about adding those.
=> enhancement: add yaml to default mime types

openapi.json
This was caught by the speakeasy regen job: https://github.com/Unstructured-IO/unstructured-python-client/actions/runs/7647985274/job/20839951777
=> Fix typo in openapi.json

prepline_general/api/general.py
The /general/v0.0.x/general path will change when we deploy a new version. This only serves to cause 404s for the users.
=> Hide the versioned endpoint in the Swagger doc

openapi.json
We're now generating the proper openapi spec via FastAPI. The problem is, if we point the Speakeasy clients to the new spec, the generated code has too much churn. All good stuff if we were releasing the clients for the first time, but now it will break compatibility. We'll need to maintain a separate openapi spec for now, and add new params here whenever they go into the server.
Example speakeasy churn: https://github.com/Unstructured-IO/unstructured-python-client/pull/42
=> fix: revert the removal of the custom openapi doc

prepline_general/api/general.py, prepline_general/api/models/form_params.py, prepline_general/api/utils.py
The purpose of this PR is to support parsing all list type parameters, including `extract_image_block_types` when calling unstructured API via unstructured client SDK (Python/JS) generated by `speakeasy`. 
Currently, the `speakeasy` doesn't generate proper client code to pass list type parameters to unstructured API because they do not expect to support specific client code for `FastAPI` that the unstructured API relies on. To address this issue, I updated the unstructured API code to parse all list type parameters passed as JSON-formatted lists (e.g. `'["image", "table"]'`).
**NOTE:** You must pass the list type parameter as a JSON-formatted list when calling unstructured API via unstructured client SDK.
(e.g. `extract_image_block_types = '["image", "table"]'`, …
=> feat: support list type parameters

openapi.json
**Summary**
In order to work from the SDK, the new chunking parameters need to appear in the `openapi.json` here.
=> fix: add overlap args

test_general/api/test_app.py
This PR updates the unit test function to test if image metadata `image_base64` and `image_mime_type` are present when `extract_image_block_types` parameter is given.
=> test: extract_image_block_types parameter usage

README.md, prepline_general/api/general.py, prepline_general/api/models/form_params.py, test_general/api/test_app.py
Issues with not receiving csv formatted answer stem from looking up `accept:` headers to derive in what format we want to send a response.
I suggest that `output_format` should be wholly in charge of this and that we get rid of raising `406` errors when there's a mismatch between accept headers and response type as user explicitly knows what format they'll get.
The only exception for it is for `multipart/mixed` but this solution does everything the same when `accept: multipart/mixed` is provided (which right now I'm not sure works over all, I didn't manage to successfully send a request through curl with this header included)
=> fix: receive csv when `output_format=text/csv`

openapi.json
Open API type for boolean is "boolean" rather than "bool".
We probably want to consider validating this file as part of the CI lint suite with:
`speakeasy validate openapi -s openapi.json`.
=> fix: data type of overlap_all parameter

CHANGELOG.md, prepline_general/api/general.py
Adds missing MIME types that are currently supported in the `unstructured` library.
=> enhancement: adds missing mimetypes supported in unstructured

README.md
This PR adds more details on "parallel mode", specifically:
- it is only recommended for the `hi_res` strategy
- client-side file splitting is supported in the Python client
Closes https://github.com/Unstructured-IO/unstructured-api/issues/378
=> readme: add more details on parallel mode

CHANGELOG.md, Makefile, README.md, scripts/app-start.sh
Modify app-start.sh so that if MAX_LIFETIME_SECONDS environmental variable is set, app will be gracefully (and later forcefully if it fails) shutdown after set amount of seconds.
=> feat: add env-variable based uvicorn app timeout

.github/workflows/docker-publish.yml, Dockerfile-amd64
I noticed that images on main branch are failing to build (and push) due to missing `-f` parameter in `docker buildx build`. By default it expects `Dockerfile` to exist, but we only have `Dockerfile-amd64` and `Dockerfile-arm64`
=> fix: build and push workflow failing due to missing `-f` option `buildx build` command

Dockerfile-amd64, Dockerfile-arm64
build and publish CI steps are failing, because the base images have changed in quay (their SHAs)
=> fix: update SHA for the base images (both architectures) after `base-images` repo update

Dockerfile-arm64
unnecessary SHA update introduced in https://github.com/Unstructured-IO/unstructured-api/pull/427 that needs to be reverted
=> fix: revert to rockylinux SHA that works (arm64)

.github/workflows/docker-publish.yml
shell syntax error occurs in docker-publish.yml workflow
=> fix: re-add `DOCKER_IMAGE` env var in `Test image` step

CHANGELOG.md, requirements/base.in, requirements/base.txt, requirements/test.txt, test_general/api/test_app.py
Bumps to `unstructured==0.15.10`.
=> version 0.0.80; bump to unstructured 0.15.10

.github/workflows/docker-publish.yml, scripts/docker-smoke-test.sh
temp disable the ARM64 build until it can be determined why its failing the CI. Need to get an updated amd64 build to quay
=> disable arm build due to failing ci

requirements/base.txt, requirements/test.txt
From the CVE scan report:
```
#!/usr/bin/env bash
major=3
minor=9
if ! python -c "import sys; assert sys.version_info.major == $major and sys.version_info.minor == $minor"; then
echo "python version not equal to expected $major.$minor: $(python --version)"
exit 1
fi
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd "$SCRIPT_DIR/../requirements" || exit
make clean
make all
popd || exit
```
=> Update h11 to remove vulnerability

prepline_general/api/models/form_params.py
This small PR resolves deprecation warnings for the `example` parameter in FastAPI's `Form` object, replacing it with the recommended `examples` parameter. These warnings are visible in the [CI logs](https://github.com/Unstructured-IO/unstructured-api/actions/runs/15281651418/job/42982178029#step:4:1697):
```python
/home/runner/work/unstructured-api/unstructured-api/prepline_general/api/models/form_params.py:54: DeprecationWarning: `example` has been deprecated, please use `examples` instead
```
=> fix: resolve FastAPI deprecation warning for example fields
