- .github/workflows/ci.yml
- Makefile
- test_general/api/test_app.py
Closes CORE-751. Most of the stuff in the previous pr has already made it to main, just some tests left over.
Verified that @MthwRobinson's curl commands in #39 are working as well.
Edit - tests seem to hang again - will poke around a bit.
> test: Add additional tests from #39

- CHANGELOG.md
- prepline_general/api/app.py
- prepline_general/api/general.py
- preprocessing-pipeline-family.yaml
- requirements/base.txt
- requirements/test.txt
Mainly for unstructured-api-tools.
> chore: requirements bumps

- README.md
~Note: This is prepped for once we confirm this build via CI on main.~
Confirmed on both m1 and dev ec2 instance
> docs: update README with notes about multi-platform

- CHANGELOG.md
- Dockerfile
- Makefile
Updated `detectron2` version to be consistent across repos.
CI should pass.
> build: sync detectron version

- CHANGELOG.md
- Dockerfile
- prepline_general/api/general.py
- preprocessing-pipeline-family.yaml
- requirements/base.txt
- requirements/test.txt
> build(deps): bump requirements

- CHANGELOG.md
- pipeline-notebooks/pipeline-general.ipynb
- prepline_general/api/general.py
- preprocessing-pipeline-family.yaml
- test_general/api/test_app.py
https://github.com/Unstructured-IO/unstructured-api/issues/83#issue-1663388581
> fix: malformed .pdf no longer results in a 500

- requirements/base.in
- requirements/base.txt
Bumps to `unstructured>=0.6.2`
> build(deps): bump unstructured version

- .github/workflows/ci.yml
- Dockerfile
- Makefile
- README.md
- Builds from pre built custom image
- Has some fixes from other branches (SSL, Makefile changes)
https://unstructured-ai.atlassian.net/browse/CORE-863?search_id=6f32eee6-c566-4a04-ba27-d14e802f55b6
> Chore: Improve image build time

- .github/workflows/create_issue.yaml
Assuming this should just work from the other repo.
> chore: copy over jira issue creator from unstructured

- CHANGELOG.md
- pipeline-notebooks/pipeline-general.ipynb
- prepline_general/api/general.py
> fix: update get API key header

- README.md
Remove outdated make target in readme
> chore: tiny readme cleanup

- CHANGELOG.md
- Dockerfile
> base image update with security patches

- .github/workflows/docker-publish.yml
fix the [build-images (linux/arm64)](https://github.com/Unstructured-IO/unstructured-api/actions/runs/5456008515/jobs/9928454700#logs) fail on main
tested build is successful on this [run action](https://github.com/Unstructured-IO/unstructured-api/actions/runs/5456251812/jobs/9928833467)
> Fix(ci): docker build driver

- CHANGELOG.md
Let's cut a release in order to deploy the latest.
> Bump api to 0.0.32

- CHANGELOG.md
- README.md
- pipeline-notebooks/pipeline-general.ipynb
- prepline_general/api/general.py
- preprocessing-pipeline-family.yaml
- test_general/api/test_app.py
forgot `m_skip_infer_table_types` is a list of str
> fix: param skip_infer_table_types should be first item from m_skip_infer_table_types 

- CHANGELOG.md
- Dockerfile
A similar update was made here:
https://github.com/Unstructured-IO/unstructured/pull/1214
> build(image): move to python3.10 from python3.8

- CHANGELOG.md
- Dockerfile
Updated versions of:
Tesseract
Leptonica
Pandoc
> bump base image version

- CHANGELOG.md
- prepline_general/api/app.py
- prepline_general/api/general.py
- preprocessing-pipeline-family.yaml
- scripts/app-start.sh
> fix: remove spurious whitespace in app-start.sh

- CHANGELOG.md
- prepline_general/api/general.py
- test_general/api/test_app.py
Closes #268 
```
import requests
filename = "sample-docs/fake-text.txt"
resp = requests.post("http://localhost:8000/general/v0/general",
files={"files": (filename, open(filename, "rb"), "application/vnd.openxmlformats-officedocument.wordprocessingml.document")},
)
resp.text
```
- PR also organizes imports into standard library, external packages, project imports.
> Catch BadZipFile errors

- .github/workflows/docker-publish.yml
Follow up from bumping the ci runners in #280
> Increase the runner sizes for the publish job

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- prepline_general/api/general.py
- requirements/base.txt
- requirements/test.txt
Note I added a workaround for [this bug](https://github.com/Unstructured-IO/unstructured/issues/1754).
> chore: bump unstructured to 0.10.23

- CHANGELOG.md
- prepline_general/api/general.py
- requirements/base.txt
- requirements/test.txt
- scripts/smoketest.py
Revert the workaround added in #285
> chore(deps): bump unstructured to 0.10.25

- Dockerfile
This includes latest version and security updates available from upstream
> Bump base image with latest security updates

- CHANGELOG.md
Need to release this version and push image to ECR by deployment-tools CI
> Chore: release 0.0.57

- Dockerfile
This adds Nvidia GPU support with CUDA to container images.
> Update base image to include CUDA 11.8

- prepline_general/api/general.py
- pyproject.toml
**Summary**
Lint, strict typing, and other refactorings to prepare `prepline_general/api/general.py` for adding basic chunking and overlap in the next PR.
Commits are groomed for easier review commit-by-commit.
> rfctr: prepare general.py for basic chunking and overlap

- test_general/api/test_app.py
Test if image metadata image_base64 and image_mime_type are present when extract_image_block_type parameter is given.
> test: test extract_image_block_type parameter

- README.md
Update the wording to:
* Clarify that this is an environment variable
* Explain how server behavior changes when the value is changed
> Update readme note on minimum free memory check

- openapi.json
**Summary**
Add the new `include_orig_elements` chunking parameter so it appears in the SDKs.
> feat: add include_orig_elements chunking parameter

- CHANGELOG.md
- requirements/base.txt
- requirements/test.txt
- scripts/smoketest.py
Bump `unstructured` dependency to 0.13.2
> chore(deps): bump unstructured to 0.13.2

- CHANGELOG.md
- scripts/parallel-mode-test.sh
Some of the output has changed in this test and it's breaking the docker build action.
https://github.com/Unstructured-IO/unstructured-api/actions/runs/8898982407/job/24437478433
> fix/Update parallel mode test to fix CI

- scripts/smoketest.py
This test is hanging and blocking the docker publish.
> Skip a pdf in make docker-test with linux/arm64

- scripts/smoketest.py
Follow up from #413. These tests hang in CI and are blocking the image build.
> fix/skip another test pdf on linux/arm64

- .github/workflows/docker-publish.yml
bug introduced in previous PR causing build failure on main
> fix: invalid env var setting in `docker-publish` workflow

- CHANGELOG.md
- requirements/base.txt
- requirements/test.txt
Bumps to `unstructured==0.15.13` to apply security patches.
> version `0.0.81`; bump to `unstructured==0.15.13`

- README.md
Updated the link for the Unstructured API documentation in the README.
> Fix Unstructured API documentation link
